---

- name: Updates apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker Module for Python
  include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker

- name: Prepare webservers
  hosts: webservers
  remote_user: root
  tasks:
    - name: Add the user 'deploy'
      ansible.builtin.user:
        name: deploy
        groups:
          - docker
        state: present

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: deploy
        key: "{{ lookup('file', public_key_path) }}"
        state: present

- name: Deploy app
  tags: deploy
  hosts: webservers
  remote_user: deploy
  tasks:
    - name: Log into DockerHub
      community.docker.docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: Run redmine container
      community.docker.docker_container:
        name: redmine-app
        image: redmine:4.2.3
        published_ports:
          - "{{ app_port }}:3000"
        restart_policy: always
        restart: yes
        container_default_behavior: no_defaults
        pull: yes
        env:
          REDMINE_DB_DATABASE: "{{ db_database }}"
          REDMINE_DB_POSTGRES: "{{ db_host }}"
          REDMINE_DB_PORT: "{{ db_port }}"
          REDMINE_DB_USERNAME: "{{ db_username }}"
          REDMINE_DB_PASSWORD: "{{ db_password }}"

- name: Setup monitoring
  tags: monitoring
  hosts: all
  gather_facts: yes
  remote_user: root
  roles:
    - name: datadog.datadog